baseURL: https://www.davidhen.com/
languageCode: en-us
theme: aafu
params:
  aboutme:
    description: I am a research fellow based at the Usher Institute and the University of Edinburgh. I use R to wrangle and analyse large administrative datasets to help inform policy and practice in health and social care. My background is in clinical nursing having worked in Acute Medical Admissions and Medical High Dependency at Raigmore Hospital in Inverness. I also worked part-time at NHS24 as a Nurse Practitioner during my PhD studies.
    icon: fas fa-user
    title: About Me
  author: David Henderson, PhD
  copyright: short copyright message
  description: Dr David Henderson
  education:
    icon: fas fa-graduation-cap
    list:
      - college: Urban Big Data Centre, University of Glasgow
        dates: 2015 - 2019
        degree: PhD in Urban Studies
        thesis_title: 'Multimorbidity and social care: exploiting emerging adminsitrative datasets in Scotland'
        thesis_url: 'http://theses.gla.ac.uk/76786/'
      - college: University of Stirling
        dates: 2013 - 2015
        degree: MRes in Health Research
      - college: University of Dundee
        dates: 2012 - 2013
        degree: PGCert in Advanced Practice
      - college: University of Stirling
        dates: 2006 - 2009
        degree: BSc in Nursing
    title: Education
  experience:
    icon: fas fa-briefcase
    list:
      - company: Usher Institute, University of Edinburgh
        dates: Jan 2021 - *Present*
        details: I work in the primary care and multimorbidity research group as part of the Centre for Population Health Sciences
        position: Research Fellow
        url: 'https://www.ed.ac.uk/profile/dr-david-henderson'
      - company: Edinburgh Napier University/Scottish Centre for Administrative Data Research
        dates: Mar 2019 - Jan 2021
        position: Research Fellow
        url: 'https://www.scadr.ac.uk/'
      - company: Urban Big Data Centre, University of Glasgow
        dates: Nov 2018 - Feb 2019
        position: Research Assistant
        url: 'https://www.ubdc.ac.uk/'
    title: Experience
  favicons:
    metas: "        <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"apple-touch-icon.png\">\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"favicon-32x32.png\">\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"favicon-16x16.png\">\n
      \       <link rel=\"manifest\" href=\"site.webmanifest\">\n        <link rel=\"mask-icon\"
      href=\"safari-pinned-tab.svg\" color=\"#252627\">\n        <link rel=\"shortcut
      icon\" href=\"favicon.ico\">\n        "
    use: yes
  hobby:
    icon: fas fa-gamepad
    list:
      - hobby: Cooking
      - hobby: Hiking
      - hobby: Baking
    title: Hobbies
  profile:
    location: City Name, ST
    name: First Last, Abbr.
    photo: profile.jpg
    tagline: Title
  project:
    icon: fas fa-project-diagram
    list:
      - description: Description of the project
        title: Project 1
        url: '#'
      - description: Description of the project
        title: Project 2
        url: '#'
      - description: Description of the project
        title: Project 3
        url: '#'
      - description: Description of the project
        title: Project 4
        url: '#'
    title: Projects
  publication:
    format:
      - date
      - authors
      - title
      - journal
    icon: fas fa-book
    list:
      - authors: F Last, F Second, P secondary
        date: '2018'
        journal: Journal of Field 52 (16), 9033-9044
        title: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua.
        type: Journal Articles
        url: '#'
      - authors: F Last, F Second, P secondary
        date: '2018'
        journal: Journal of Field 52 (16), 9033-9044
        title: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua.
        type: Journal Articles
        url: '#'
      - authors: F Last, F Second, P secondary
        date: '2018'
        journal: Journal of Field 52 (16), 9033-9044
        title: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua.
        type: Proceedings
        url: '#'
    title: Publications
    types:
      - Journal Articles
      - Proceedings
  showInAccordion:
    - expand: yes
      item: aboutme
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  skill:
    icon: fas fa-cogs
    list:
      - skill: Skill 1, Skill 2
        skillrating: 90
      - skill: Skill 3
        skillrating: 80
      - skill: Skill 4
        skillrating: 50
    panelId: skill-panel
    title: Skills
  social:
    list:
      - icon: fab fa-linkedin-in
        title: LinkedIn
        url: '#'
      - icon: fab fa-stack-overflow
        title: StackOverflow
        url: '#'
      - icon: fab fa-github
        title: GitHub
        url: '#'
      - icon: fab fa-twitter
        title: Twitter
        url: '#'
      - icon: fab fa-orcid
        title: Orcid
        url: '#'
      - icon: ai ai-google-scholar
        title: Google Scholar
        url: '#'
      - icon: fab fa-researchgate
        title: ResearchGate
        url: '#'
    title: Links
  theme:
    mainTheme: ocean
    showAttribute: yes
    singlePage: no
  title: Aafu theme
