baseURL: https://www.davidhen.com/
languageCode: en-us
theme: aafu
params:
  aboutme:
    description: I am a Research Fellow based with the primary care and multimorbidity research group at the Usher Institute, University of Edinburgh. I am responsible for delivering the quantitative elements of an Economic \& Social Research Council-funded grant evaluating transformation of primary care. I have particular skills utilising R to clean and analyse large administrative datasets for epidemiology and health \& care services research. I am also a registered Nurse and until recently worked part-time for NHS 24 as a Nurse Practitioner. Previous nursing experience included Medical High Dependency and Acute Medical Admissions at Raigmore Hospital in Inverness.
    icon: fas fa-user
    title: About Me
  author: David Henderson, PhD
  copyright: 
  description: Dr David Henderson
  education:
    icon: fas fa-graduation-cap
    list:
      - college: Urban Big Data Centre, University of Glasgow
        dates: 2015 - 2019
        degree: PhD in Urban Studies
        thesis_title: 'Multimorbidity and social care: exploiting emerging adminsitrative datasets in Scotland'
        thesis_url: 'http://theses.gla.ac.uk/76786/'
      - college: University of Stirling
        dates: 2013 - 2015
        degree: MRes in Health Research
      - college: University of Dundee
        dates: 2012 - 2013
        degree: PGCert in Advanced Practice
      - college: University of Stirling
        dates: 2006 - 2009
        degree: BSc in Nursing
    title: Education
  experience:
    icon: fas fa-briefcase
    list:
      - company: Usher Institute, University of Edinburgh
        dates: Jan 2021 - *Present*
        details: I work in the primary care and multimorbidity research group as part of the Centre for Population Health Sciences
        position: Research Fellow
        url: 'https://www.ed.ac.uk/profile/dr-david-henderson'
      - company: Edinburgh Napier University/Scottish Centre for Administrative Data Research
        dates: Mar 2019 - Jan 2021
        position: Research Fellow
        url: 'https://www.scadr.ac.uk/'
      - company: Urban Big Data Centre, University of Glasgow
        dates: Nov 2018 - Feb 2019
        position: Research Associate
        url: 'https://www.ubdc.ac.uk/'
      - company: NHS24
        dates: Jun 2015 - Oct 2018
        position: Nurse Practitioner
      - company: NHS Highland
        dates: June 2011 - June 2015
        position: Staff Nurse
        details: Acute Medical Admissions & Medical High Dependency Unit 
      - company: NHS Highland
        dates: Apr 2010 - June 2011
        position: Staff Nurse
        details: Cardiology step-down & General Medical ward
      - company: NHS Highland
        dates: Jan 2008 - April 2010
        position: Healthcare Assistant
        details: Nurse Bank
      - company: Self-employed
        dates: Jul 2003 - Sept 2006
        position: Assistant Director & Locations Scout
        details: Worked for many media companies including BBC and STV on a variety of broadcast programming including drama and live productions
      - company: HM Forces
        dates: Nov 1995 - Oct 2002
        position: Lance Corporal
        details: Infantry soldier in 1st Battalion the Highlanders (Seaforth, Gordons & Camerons). Main duties as a drummer in the regiment's Pipe's and Drums and as a platoon signaller in the machine gun (GPMG/SF) platoon
    title: Experience
  favicons:
    metas: "        <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"apple-touch-icon.png\">\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"favicon-32x32.png\">\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"favicon-16x16.png\">\n
      \       <link rel=\"manifest\" href=\"site.webmanifest\">\n        <link rel=\"mask-icon\"
      href=\"safari-pinned-tab.svg\" color=\"#252627\">\n        <link rel=\"shortcut
      icon\" href=\"favicon.ico\">\n        "
    use: yes
  hobby:
    icon: fas fa-gamepad
    list:
      - hobby: Pipe Band Drumming
      - hobby: Golf
      - hobby: Walking
      - hobby: Reading
    title: Hobbies
  profile:
    location: Highlands, Scotland
    name: David Henderson, PhD
    photo: me.png
    tagline: Research Fellow
  project:
    icon: fas fa-project-diagram
    list:
      - description: Website associated with the above paper showing code for measures and plots used in the report
        title: COVID-19 mortality and long-term care- a UK comparison
        url: 'https://davidhen.github.io/ltc_covid_uk/index.html'
      - description: Link to GitHub repo showing the RMarkdown files I used to write my thesis.
        title: PhD Thesis
        url: 'https://github.com/davidhen/thesis_rmd'
    title: Projects
  publication:
    format:
      - date
      - authors
      - title
      - journal
    icon: fas fa-book
    list:
      - authors: MacRae C, Henderson D (joint first-author), Mercer SW, Burton J, De Souza N, Grill P, Marwick C, Guthrie B.
        date: 'In Print'
        journal: British Journal of General Practice Open
        title: Excessive polypharmacy and potentially inappropriate prescribing in 147 care homes- cross sectional study
        type: First/last and/or corresponding author
        url: '#'
      - authors: Henderson D, Atherton I, McCowan C, Mercer SW, Bailey N.
        date: '2021'
        journal: Age & Ageing 50(1)
        title: Linkage of national health & social care data- a cross-sectional study of multimorbidity and social care use in people aged over 65 years in Scotland
        type: First/last and/or corresponding author
        url: 'https://doi.org/10.1093/ageing/afaa134'
      - authors: MacRae C, Mercer SW, Guthrie, B, Henderson D.
        date: '2021'
        journal: British Journal of General Practice 71(704)
        title: Comorbidity in chronic kidney disease- a large cross-sectional study of prevalence in Scottish primary care
        type: First/last and/or corresponding author
        url: 'https://doi.org/10.3399/bjgp20X714125'
      - authors: Henderson D, Burton J, Lynch E, Clark D, Rintoul J, Bailey N.
        date: 2019
        title: Data Resource Profile- The Scottish Social Care Survey (SCS) and the Scottish Care Home Census (SCHC)
        journal: International Journal of Population Data Science 4(1)
        url: 'https://doi.org/10.23889/ijpds.v4i1.1108'
        type: First/last and/or corresponding author
      - authors: Mercer SW, Henderson D, Huang H, Stewart E, Guthrie B, Wang H.
        date: '2021'
        journal: British Journal of General Practice
        title: Integration of health and social care - necessary but challenging for all
        type: Other academic publications
        url: '#'
      - authors: Huang H, Donaghy E, Henderson D, Wang H, Mercer SW.
        date: 'submitted'
        journal: Family Medicine and Community health
        title: Using self-determination theory in research and evaluation in primary care.
        type: Other academic publications
        url: '#'
      - authors: Comas-Herrera A, Zalakaín J, Lemmon E, Henderson D, Litwin C, Hsu AT, Schmidt AE, Arling G, Kruse F, Fernández JL.
        date: 2021
        journal: International Long Term Care Policy Network
        title: Mortality associated with COVID-19 in care homes- international evidence. 
        type: Other academic publications
        url: 'https://ltccovid.org/2020/04/12/mortality-associated-with-covid-19-outbreaks-in-care-homes-early-international-evidence/'
      - authors: Bell D, Comas-Herrera A, Henderson D, Jones S, Lemmon E, Moro M, Murphy S, o'Reilly D, Patrignani P.
        date: 2020
        journal: International Long Term Care Policy Network
        title: COVID-19 mortality and long-term care- A UK comparison.
        type: Other academic publications
        url: 'https://ltccovid.org/2020/08/28/covid-19-mortality-and-long-term-care-a-uk-comparison/'
      - authors: Bell D, Henderson D, Lemmon E, Moro M.
        date: 2020
        journal: International Long Term Care Policy Network
        title: Deaths in Scottish care homes and COVID-19
        type: Other academic publications
        url: 'https://ltccovid.org/wp-content/uploads/2020/12/Deaths-in-Scottish-care-homes-up-to-3rd-June-corrected-1.pdf'
    title: Academic outputs
    types:
      - First/last and/or corresponding author
      - Other academic publications
      - Conference Proceedings
      - Grants
      - PhD supervision
  showInAccordion:
    - expand: yes
      item: aboutme
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  skill:
    icon: fas fa-cogs
    list:
      - skill: Skill 1, Skill 2
        skillrating: 90
      - skill: Skill 3
        skillrating: 80
      - skill: Skill 4
        skillrating: 50
    panelId: skill-panel
    title: Skills
  social:
    list:
      - icon: fab fa-linkedin-in
        title: LinkedIn
        url: '#'
      - icon: fab fa-stack-overflow
        title: StackOverflow
        url: '#'
      - icon: fab fa-github
        title: GitHub
        url: '#'
      - icon: fab fa-twitter
        title: Twitter
        url: '#'
      - icon: fab fa-orcid
        title: Orcid
        url: '#'
      - icon: ai ai-google-scholar
        title: Google Scholar
        url: '#'
      - icon: fab fa-researchgate
        title: ResearchGate
        url: '#'
    title: Links
  theme:
    mainTheme: ocean
    showAttribute: yes
    singlePage: no
  title: Aafu theme
